kpi_equivalents = {
    "Measures = Weighted R_VOL1": "Volumen",
    "Measures = Weighted R_VOL1 Vert %": "Share Volumen",
    "Measures = Weighted VAL_LC": "Facturación",
    "Measures = Weighted VAL_LC Vert %": "Share Valor",
    "Measures = Weighted PENET": "Penetración %",
    "Measures = Weighted VO1_BUY": "Compra media",
    "Measures = Weighted VALC_BUY": "Gasto medio",
    "Measures = Weighted VO1_DAY": "Compra por acto",
    "Measures = Weighted VALC_DAY": "Ticket",
    "Measures = Weighted FREQ": "Frecuencia",
    "Measures = Weighted PM1_LC": "Precio medio",
    "Measures = Weighted VOL1_P": "Volumen proyectado 000s",
    "Measures = Weighted VOL1_P Vert %": "Share Volumen",
    "Measures = Weighted VAL_LC_P Vert %": "Share Valor",
    "Measures = Weighted VOL1_BUY": "Volumen Medio",
    "Measures = Weighted VOL1_DAY": "Volumen por ocasión",
    "Measures = Weighted UNIT_DAY": "Unidades por acto",
    "Measures = Weighted FR_DAYS": "Frecuencia",
    "Measures = Weighted VAL_LC_P": "Valor proyectado 000s",
    "Measures = BUYERS": "Compradores",
    #Agregados para los de fuera de PVARIAB
    "Measures = Weighted VOL2_PCO": "Volumen (Lt. '000)",
    "Measures = Weighted VOL2_PCO Vert %": "Share Volumen",
    "Measures = Weighted VOL2_BUY": "Compra Media",
    "Measures = Weighted VOL2_DAY": "Compra x Acto",
    "Measures = Weighted PM2_LC": "Precio Medio",

}
